export * from './auth.service';
import { AuthService } from './auth.service';
export * from './chat.service';
import { ChatService } from './chat.service';
export * from './client.service';
import { ClientService } from './client.service';
export * from './commentaire.service';
import { CommentaireService } from './commentaire.service';
export * from './historiqueAction.service';
import { HistoriqueActionService } from './historiqueAction.service';
export * from './marketSegment.service';
import { MarketSegmentService } from './marketSegment.service';
export * from './notification.service';
import { NotificationService } from './notification.service';
export * from './rFQ.service';
import { RFQService } from './rFQ.service';
export * from './rapport.service';
import { RapportService } from './rapport.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './versionRFQ.service';
import { VersionRFQService } from './versionRFQ.service';
export * from './worker.service';
import { WorkerService } from './worker.service';
export const APIS = [AuthService, ChatService, ClientService, CommentaireService, HistoriqueActionService, MarketSegmentService, NotificationService, RFQService, RapportService, UserService, VersionRFQService, WorkerService];
