/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RFQSummaryDto } from './rFQSummaryDto';


export interface ClientDetailsDto { 
    id?: number;
    nom?: string | null;
    email?: string | null;
    sales?: string | null;
    rfQs?: Array<RFQSummaryDto> | null;
}

