/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RFQ } from './rFQ';


export interface Client { 
    id?: number;
    nom?: string | null;
    email?: string | null;
    sales?: string | null;
    rfQs?: Array<RFQ> | null;
}

