/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CommentaireDto { 
    id?: number;
    contenu?: string | null;
    dateC?: string;
    validateurId?: number;
    nomUser?: string | null;
}

