/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { RFQ } from './rFQ';
import { VersionRFQ } from './versionRFQ';


export interface Commentaire { 
    id?: number;
    contenu?: string | null;
    dateC?: string;
    validateur?: User;
    validateurId?: number;
    rfqId?: number | null;
    rfq?: RFQ;
    versionRFQId?: number | null;
    versionRFQ?: VersionRFQ;
}

