/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCommentaireDto { 
    contenu?: string | null;
    rfqId?: number | null;
    versionRFQId?: number | null;
}

