/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleU } from './roleU';


export interface CreateUserDto { 
    nomUser?: string | null;
    email?: string | null;
    password?: string | null;
    role?: RoleU;
}
export namespace CreateUserDto {
}


