/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateHistoriqueActionDto { 
    type?: string | null;
    cibleAction?: string | null;
    referenceCible?: string | null;
    detailsAction?: string | null;
    dateAction?: string;
    userId?: number;
}

