/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RFQ } from './rFQ';
import { VersionRFQ } from './versionRFQ';


export interface MarketSegment { 
    id?: number;
    nom?: string | null;
    versions?: Array<VersionRFQ> | null;
    rfQs?: Array<RFQ> | null;
}

