/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationDto { 
    id?: number;
    message?: string | null;
    createdAt?: string;
    isRead?: boolean;
    rfqId?: number | null;
}

