/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Rapport { 
    id?: number;
    cheminFichier?: string | null;
    dateCreation?: string;
    user?: User;
    userId?: number;
}

