/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ReclamationType = 0 | 1 | 2;

export const ReclamationType = {
    NUMBER_0: 0 as ReclamationType,
    NUMBER_1: 1 as ReclamationType,
    NUMBER_2: 2 as ReclamationType
};

