/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RoleU = 0 | 1 | 2 | 3;

export const RoleU = {
    NUMBER_0: 0 as RoleU,
    NUMBER_1: 1 as RoleU,
    NUMBER_2: 2 as RoleU,
    NUMBER_3: 3 as RoleU
};

