/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Statut = 0 | 1;

export const Statut = {
    NUMBER_0: 0 as Statut,
    NUMBER_1: 1 as Statut
};

