/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReclamationStatus } from './reclamationStatus';


export interface UpdateReclamationStatusDto { 
    status?: ReclamationStatus;
}
export namespace UpdateReclamationStatusDto {
}


