/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleU } from './roleU';


export interface UserSummaryDto { 
    id?: number;
    nomUser?: string | null;
    email?: string | null;
    image?: string | null;
    role?: RoleU;
    password?: string | null;
}
export namespace UserSummaryDto {
}


