/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Rapport } from './rapport';
import { Reclamation } from './reclamation';
import { HistoriqueAction } from './historiqueAction';
import { RoleU } from './roleU';
import { Commentaire } from './commentaire';
import { RFQ } from './rFQ';
import { VersionRFQ } from './versionRFQ';


export interface User { 
    id?: number;
    nomUser?: string | null;
    email?: string | null;
    password?: string | null;
    image?: string | null;
    role?: RoleU;
    commentaires?: Array<Commentaire> | null;
    historiqueActions?: Array<HistoriqueAction> | null;
    rapports?: Array<Rapport> | null;
    rfQsEnTantQueIngenieur?: Array<RFQ> | null;
    rfQsEnTantQueValidateur?: Array<RFQ> | null;
    versionRFQsEnTantQueIngenieur?: Array<VersionRFQ> | null;
    versionRFQsEnTantQueValidateur?: Array<VersionRFQ> | null;
    reclamations?: Array<Reclamation> | null;
}
export namespace User {
}


