/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarketSegment } from './marketSegment';
import { Statut } from './statut';
import { User } from './user';
import { Worker } from './worker';
import { Commentaire } from './commentaire';
import { RFQ } from './rFQ';


export interface VersionRFQ { 
    codeV?: number;
    quoteName?: string | null;
    numRefQuoted?: number;
    sopDate?: string | null;
    maxV?: number;
    estV?: number;
    koDate?: string | null;
    customerDataDate?: string | null;
    mdDate?: string | null;
    mrDate?: string | null;
    tdDate?: string | null;
    trDate?: string | null;
    ldDate?: string | null;
    lrDate?: string | null;
    cdDate?: string | null;
    approvalDate?: string | null;
    dateCreation?: string;
    statut?: Statut;
    materialLeader?: Worker;
    materialLeaderId?: number | null;
    testLeader?: Worker;
    testLeaderId?: number | null;
    marketSegment?: MarketSegment;
    marketSegmentId?: number | null;
    rfq?: RFQ;
    rfqId?: number;
    commentaires?: Array<Commentaire> | null;
    ingenieurRFQ?: User;
    ingenieurRFQId?: number | null;
    validateur?: User;
    validateurId?: number | null;
}
export namespace VersionRFQ {
}


