/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Statut } from './statut';


export interface VersionRFQDetailsDto { 
    cq?: number | null;
    quoteName?: string | null;
    numRefQuoted?: number | null;
    rfqId?: number;
    valide?: boolean;
    rejete?: boolean;
    sopDate?: string | null;
    maxV?: number | null;
    estV?: number | null;
    statut?: Statut;
    koDate?: string | null;
    customerDataDate?: string | null;
    mdDate?: string | null;
    mrDate?: string | null;
    tdDate?: string | null;
    trDate?: string | null;
    ldDate?: string | null;
    lrDate?: string | null;
    cdDate?: string | null;
    approvalDate?: string | null;
    dateCreation?: string;
    rfqQuoteName?: string | null;
    materialLeader?: string | null;
    testLeader?: string | null;
    marketSegment?: string | null;
    ingenieurRFQ?: string | null;
    vaLeader?: string | null;
}
export namespace VersionRFQDetailsDto {
}


