/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MarketSegment } from './marketSegment';
import { Statut } from './statut';
import { User } from './user';
import { Worker } from './worker';
import { Commentaire } from './commentaire';
import { Client } from './client';
import { RFQ } from './rFQ';


export interface VersionRFQ { 
    id?: number;
    cq?: number;
    quoteName?: string | null;
    numRefQuoted?: number | null;
    sopDate?: string | null;
    maxV?: number | null;
    estV?: number | null;
    koDate?: string | null;
    customerDataDate?: string | null;
    mdDate?: string | null;
    mrDate?: string | null;
    tdDate?: string | null;
    trDate?: string | null;
    ldDate?: string | null;
    lrDate?: string | null;
    cdDate?: string | null;
    approvalDate?: string | null;
    dateCreation?: string;
    statut?: Statut;
    valide?: boolean;
    rejete?: boolean;
    brouillon?: boolean;
    materialLeader?: Worker;
    materialLeaderId?: number | null;
    testLeader?: Worker;
    testLeaderId?: number | null;
    marketSegment?: MarketSegment;
    marketSegmentId?: number | null;
    rfq?: RFQ;
    rfqId?: number;
    commentaires?: Array<Commentaire> | null;
    ingenieurRFQ?: User;
    ingenieurRFQId?: number | null;
    vaLeader?: User;
    vaLeaderId?: number | null;
    client?: Client;
    clientId?: number;
    fileName?: string | null;
    fileContentType?: string | null;
    fileData?: string | null;
}
export namespace VersionRFQ {
}


