/**
 * GestionRFQ API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleW } from './roleW';
import { RFQ } from './rFQ';
import { VersionRFQ } from './versionRFQ';


export interface Worker { 
    id?: number;
    nom?: string | null;
    role?: RoleW;
    vMaterialLeader?: Array<VersionRFQ> | null;
    vTestLeader?: Array<VersionRFQ> | null;
    asMaterialLeader?: Array<RFQ> | null;
    asTestLeader?: Array<RFQ> | null;
}
export namespace Worker {
}


